{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubepyramid.serviceAccountName" . }}
  labels:
    {{- include "kubepyramid.labels" . | nindent 4 }}
{{- end }}
